### ISSUE TITLE
Neovim doenst work

### ISSUE THREAD

**Issue by alnavv** [JamshedVesuna/vim-markdown-preview#46] opened 2016-10-02 14:07 UTC
It works perfect when opening the document with vim, but it does not renders the page when opening the document with neovim (neovim opens the web-explorer with the page ... but it is blank page).
So, i just open the *.md with vim, but (to mention that) i don't have an specific vim configuration, but the following:
ln -s ~/.config/nvim ~/.vim
ln -s ~/.config/nvim/init.vim ~/.vimrc
so, in vim i am only using the neovim configuration (case this info can be useful).
Cheers,
  A.

**Comment by Kinmarui** [comment] 2017-03-06 22:04
Hi I'm using this configuration and everything works for me, are you sure you don't have some extra configuration for nvim?. 
https://github.com/rafi/vim-config

Note: I'm using fish shell, but that shouldn't be a problem

**Comment by JamshedVesuna** [comment] 2017-03-16 16:52
@alnavv I'm having trouble reproducing this issue. It sounds like your [markdown requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements) are not working in neovim, which may be a configuration issue. Can you confirm that your neovim is only using your vim configuration?

**Comment by JamshedVesuna** [comment] 2017-05-29 22:11
Closing this out for now, feel free to reopen (see my comment above).

**Closed by JamshedVesuna** 2017-05-29 22:11 UTC
