### ISSUE TITLE
Blank preview

### ISSUE THREAD

**Issue by micjoh** [JamshedVesuna/vim-markdown-preview#44] opened 2016-08-17 20:43 UTC
I get a blank preview.

macos sierra with safari. latest macvim

**Comment by JamshedVesuna** [comment] 2016-08-17 21:29
Have you installed the [Requirements](https://github.com/JamshedVesuna/vim-markdown-preview#requirements) for macOS? What happens if you run the command manually? Either `markdown README.md > out.html`? or `grip README.md --export out.html`?

**Comment by micjoh** [comment] 2016-08-18 21:29
I have now reinstalled both markdown and grip through homwbrew.
If I run the commands manually it renders correctly. IE out.html shows the file correctly.

I have intalled with plug plugin manager and also manually.

in my vimrc I have:
let vim_markdown_preview_toggle=2
let vim_markdown_preview_hotkey='<C-m>'
" let vim_markdown_preview_browser='Google Chrome'
" let vim_markdown_preview_github=1  

I have tried all variations with the browser and github. No change

I think it is the preview-hotkey that doesn’t work.

I have switched hotkeys with ctrlP that I also use and ctrlP works all the time but this plugin acts as if the hotkey wasn’t registrered

br /michael

**Comment by JamshedVesuna** [comment] 2016-08-24 06:25
It looks like you're trying to use two conflicting options. 
`let vim_markdown_preview_toggle=2` means that every time you write/save the buffer, a browser preview will be rendered, as intended. See [Toggle Options](https://github.com/JamshedVesuna/vim-markdown-preview#toggle).

Thus, you can't _also_ use `let vim_markdown_preview_hotkey='<C-m>'` as an additional shortcut for calling the vim markdown preview plugin. 

If you remove `let vim_markdown_preview_toggle=2` from your vimrc, it should work. Otherwise, your current configuration should work every time you write to the buffer.

**Comment by JamshedVesuna** [comment] 2016-08-31 23:36
Closing this for now. Feel free to re-open.

**Closed by JamshedVesuna** 2016-08-31 23:36 UTC
